FROM arm32v7/python:3.7-slim-buster

WORKDIR /app

RUN apt update && apt install -y \
    python3 \
    python3-dev \
    python3-pip \
    libglib2.0-dev

RUN pip3 install pyserial
RUN pip3 install scd30_i2c

COPY requirements.txt ./
RUN pip install -r requirements.txt


COPY . .

CMD [ "python3", "-u", "./main.py" ]